# traduzindo dados com `Google Translate` no `Pandas.DataFrame()`
## O DataSet contém os dados da Evolução da analise de dados
lib: pip install googletrans

In [1]:
!head -n1 data_analysis.csv

Year,Decade,Milestone Title,Milestone Event,Why Important,Reference,People Process or Technology Tag

In [2]:
import pandas
from googletrans import Translator
tradutor = Translator()

In [3]:
lista = ['Year','Milestone Title','Milestone Event','Why Important','Reference']
listacols = ['ano','descricao','eventos','observacao','link_referencia']

df = pandas.read_csv("data_analysis.csv", sep=",", usecols = lista)
df.columns = listacols
df.head(15)

,ano,descricao,eventos,observacao,link_referencia
0,1945,ENIAC,First electronic general-purpose computer = ENIAC,Faster decisions using a computer and mathmatics,https://en.wikipedia.org/wiki/ENIAC
1,1945,John von Neumann / array,John von Neumann creates a merge sort algorith...,"Arrays allow mathmatics, grouping and sorting ...",https://en.wikipedia.org/wiki/John_von_Neumann
2,1956,First Hard Disk,The first computer hard disk used,Storing data for reuse = reduces time to recre...,https://fiftiesweb.com/pop/inventions/
3,1958,Modem,The modem invented,"Communication between computers, foundation of...",https://fiftiesweb.com/pop/inventions/
4,1961,John Tukey / data analysis,Statistician John Tukey defined data analysis,Defined the process and procedures of collecti...,https://projecteuclid.org/download/pdf_1/eucli...
5,1970,Dr. EF Codd / normalized data,"Dr. E.F. Codd creates concept of ""normalizing ...",Made data independent from specific software /...,https://www.seas.upenn.edu/~zives/03f/cis550/c...
6,1972,FORTRAN supports CSV Files,FORTRAN Programing Language supports comma sep...,Programing Language can input / output data fi...,http://bitsavers.trailing-edge.com/pdf/ibm/370...
7,1982,Mike Bloomberg / Terminal,Bloomberg Terminal Introduced,Financial Data Analysis of Bond Market to mark...,https://www.bloomberg.com/company/press/timeli...
8,1983,Edward Tufty / Data Viz concepts,"Edward Tufty writes the book ""The Visual Displ...",Defines ways to communicate with data beyond t...,https://www.amazon.com/gp/product/096139210X/r...
9,1986,SQL Standardized,SQL Language Standardized across all database ...,A common language agnostic to technology for s...,https://blog.ansi.org/2018/10/sql-standard-iso...
10,1987,MS Excel,Microsoft Excel,Mainstream productivity software available to ...,https://en.wikipedia.org/wiki/Microsoft_Excel
11,1989,BI (Business Intelligence),The term “BI (Business Intelligence)” was prop...,Data becomes as Asset = used for analysis to m...,https://www.flydata.com/blog/a-brief-history-o...
12,1990,OLAP,On-Line Analytical Processing (OLAP) and Busin...,"Data Volumes Increase, specialized software an...",http://dssresources.com/history/dsshistory.html
13,1990,Guido van Rossum / Python,Guido van Rossum creates the Python programmin...,Programming language that has versility beyond...,NaN
14,1991,Linus Torvalds / Linux OS,Finnish engineer Linus Torvalds introduces the...,Open Source software and Programming Languages...,https://www.bloomberg.com/news/articles/2014-1...

In [4]:
'''
essa função detecta se os dados da coluna são "en" de ingles 
e traduz para portugues
'''
def traduzir(value):
    if str(tradutor.detect(value))[14:16] == "en":
        td = tradutor.translate(value, src="en", dest="pt")
        return td.text

In [5]:
'agora vamos traduzir os dados da coluna "Importancia"'
df['traduzido'] = df.observacao.map(traduzir)

'dados da coluna "observacao" traduzidos para "traduzido"'
df[['ano','descricao','traduzido']]

,ano,descricao,traduzido
0,1945,ENIAC,decisões mais rápidas usando um computador e m...
1,1945,John von Neumann / array,"Arrays permitir mathmatics, agrupamento e clas..."
2,1956,First Hard Disk,O armazenamento de dados para reutilização = r...
3,1958,Modem,"Comunicação entre computadores, base da Intern..."
4,1961,John Tukey / data analysis,Definido o processo e os procedimentos de reco...
5,1970,Dr. EF Codd / normalized data,dados feitas independentes de software / lingu...
6,1972,FORTRAN supports CSV Files,arquivos de dados de entrada pode / saída prog...
7,1982,Mike Bloomberg / Terminal,Financeira Análise de Dados de Mercado de Obri...
8,1983,Edward Tufty / Data Viz concepts,Define formas de comunicar com dados além tabe...
9,1986,SQL Standardized,Um agnóstico linguagem comum para a tecnologia...
10,1987,MS Excel,software de produtividade Mainstream disponíve...
11,1989,BI (Business Intelligence),Os dados se torna tão ativo = utilizado para a...
12,1990,OLAP,"Volumes Aumento, software especializado e habi..."
13,1990,Guido van Rossum / Python,Linguagem de programação que tem versility alé...
14,1991,Linus Torvalds / Linux OS,de software e programação Open Source Línguas ...
15,1993,Bill Inmon / Data Warehouse,Organizar os dados de forma a obter insights e...
16,1993,QlikView,Tecnologia disruptiva que remove as barreiras ...
17,1996,Ralph Kimball / Kimball Methodology,Permite o crescimento do analista de dados e b...
18,1996,XML Created,"Os objetivos do XML enfatiza a simplicidade, g..."
19,1997,Data Mining defined,Evoluindo Data Mining como uma habilidade se a...
20,1998,Carlo Strozzi / NoSQL,estruturas definidas removidos exigidos pelo B...
21,2000,REST / APIs,Dados Democracia = Se eu posso usar um navegad...
22,2001,Natural Language (NLP) Toolkit,estatística processamento de linguagem natural...
23,2001,JSON,"Evoluíram a partir de XML, dados agnósticos pa..."
24,2004,Stephen Few,dados evolui viz como uma habilidade e meios e...
25,2004,Facebook,A Rede Social influencia as pessoas e os dados...
26,2005,Google Analytics,Um motor de busca na web e metadados (dados so...
27,2006,Apache Hadoop,Os Lago de dados oferece alternativas para dat...
28,2006,NumPy,biblioteca linguagem Python cresce além de pro...
29,2006,Twitter,Unstructured Big Data oferece oportunidades pa...
30,2006,AWS,Cloud computing = limites para computadores fí...
31,2007,Github,O controle de versão e partilha de código entr...
32,2007,iPhone,Móvel Analytics se torna uma indústria
33,2008,Pandas,Python evolui para a ferramenta de análise de ...
34,2009,Uber,Usando dados e Tecnologia para perturbar a ind...
35,2010,Kaggle.com,Dados Democracy in action = QUALQUER UM recomp...
36,2011,Naomi Robbins,Engenheiro pioneiro Mulher e especialista em v...
37,2012,Raspberry PI,Fazer o IOT (Internet of Things) escala massa ...
38,2012,Alberto Cairo,Charts se tornar uma forma de arte e carreiras...
39,2015,Jupyter Notebook,Abrir código-fonte e bibliotecas torna-se um t...
40,2015,Alexa,Fazendo voz para integrar dados e permitindo a...
41,2018,The Data Literacy Project,A construção de uma cultura orientada dados on...

# e Por fim

In [6]:
frase = (2020 - int(str(df[(df["eventos"].str.contains("Pyth" ,na=False))]['ano'])[6:10]))
print("\n")
print('Ano do nascimento do Python, e já fazem '+str(frase)+" anos dessa linguagem incrível")
print("========="* 8)
df[(df["eventos"].str.contains("Pyth" ,na=False))][['ano','descricao','traduzido']]

Ano do nascimento do Python, e já fazem 30 anos dessa linguagem incrível
========================================================================

,ano,descricao,traduzido
13,1990,Guido van Rossum / Python,Linguagem de programação que tem versility alé...